Rework the README to put the tutorial front and center.
TraceMachina/lucene-on-gpu pull request #1
Opened 2024-07-28 02:35 UTC by MarcusSorealheis

here is an attempt to rework the README

2024-07-28 02:35 UTC, MarcusSorealheis commented
<img width="1261" alt="image" src="https://github.com/user-attachments/assets/ed115296-b080-4c6b-a694-a33f920cb84b">

2024-07-28 07:01 UTC, aaronmondal requested changes
The image and the brev approach are super nice!

- Double-check that the image is actually rendering correctly. In your fork it's currently not displayed (viewed on a mac/chrome)
- The buildsystem changes obsolete most of the previous setup and need to be adjusted.
- It looks like there are some more leftover pointers to the old repo in this readme. We should probably remove those.

2024-07-28 07:01 UTC, aaronmondal commented on README.md
> +  <hnswBeamWidth>
This is obsolete. It's all part of the bazel invocation.

2024-07-28 07:01 UTC, aaronmondal commented on README.md
> +14. mvn -version
This section is obsolete. The way to set up an instance now is the setup in the 'Setup' section below. If you want a copy-paste variant, it probably looks something like this:

```bash
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
# TODO there will be some command printed after the installation to refresh the shell.
git clone git clone https://github.com/TraceMachina/lucene-on-gpu
cd lucene on gpu
nix develop
bazel run lucene
```

2024-07-28 16:52 UTC, MarcusSorealheis commented on README.md
> +  <hnswBeamWidth>
can you link me to the new changes? That would make sense. I will test them.

2024-07-28 16:53 UTC, MarcusSorealheis commented on README.md
> +14. mvn -version
oh wow

2024-07-28 16:55 UTC, MarcusSorealheis commented on README.md
> +14. mvn -version
are the steps for indexing data still relevant.

2024-07-29 13:42 UTC, aaronmondal commented on README.md
> +14. mvn -version
Nah it's all automated :P

If you take a look at the commands, it's basically all just environment setup for nix. Once you have that the only thing that needs to be run is the `bazel run lucene` command which prepares all the dependencies for this shellscript:

https://github.com/TraceMachina/lucene-on-gpu/blob/main/lucene/demo.sh

Building the executable in this script and the fetching the dataset etc all happen as part of the invocation.

The nix environment prepares CUDA, then some custom Bazel overlays sparsely build the part of CuVS that is required. The only thing that you might need to change, depending on your GPU model is this line here which specifies the GPU target architecture:

https://github.com/TraceMachina/lucene-on-gpu/blob/ed82e370ed2c8ce43e5ada2fd7cd3d98654de35b/thirdparty/global_defs.bzl#L6

IIRC the code likely works on GPUs newer than this architecture, but it won't work on older GPUs. Also, the lower you set this the less "specific" or "modern" optimizations you'll get. So for best performance you'd want to set this to exactly the architecture of the GPU that you intend to run it on. Here is a list:

https://developer.nvidia.com/cuda-gpus

2024-07-29 13:43 UTC, aaronmondal commented on README.md
> +  <hnswBeamWidth>
The instructions are in the README.

2024-07-29 13:44 UTC, aaronmondal commented on README.md
> +  <hnswBeamWidth>
https://github.com/TraceMachina/lucene-on-gpu?tab=readme-ov-file#%EF%B8%8F-setup

2024-07-29 17:46 UTC, aaronmondal commented
LGTM!

Note that we'll need to update the docs on the specific setup of the brev nodes a bit. It'll only work on Ubuntu 24.04 images. I believe even a "raw" 24.04 image would work, but I'm still testing. In any case, this LGTM and we can fix the brev setup later.

2024-07-29 17:46 UTC, merged